### ISSUE TITLE
Add a command to compile a file to .wasm

### ISSUE THREAD

**Issue by amirouche** [google/schism#86]
It would be nice to have a command that compiles Scheme file to `.wasm` from the repository.

Something like:

```bash
./compile.sh input.scm out.wasm
```

**Comment by amirouche** [comment]
There is `schism.ss` but using it with `guile schism.ss` or `scheme schism.ss` doesn't work.

Here is the Chew error:

```scheme
Exception: multiple definitions for filter and memq in body (library (schism compiler) (export compile-library compile-stdin->stdout) (import (rnrs) (rnrs mutable-pairs) (only (...) gensym)) (define (void) (when #f #f)) (define (trace-value x) (write x) (newline) x) ...) at line 15, char 1 of schism/compiler.ss
```

**Comment by amirouche** [comment]
Ah there is also `schism.sh` but that one fails also:

```javascript
$ bash schism.sh test/lambda-1.ss 
(node:20549) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/esm/default_resolve.js:59
  let url = moduleWrapResolve(specifier, parentURL);
            ^

Error: Cannot find module '/home/amirouche/src/scheme/schism/gcli' imported from /home/amirouche/src/scheme/schism/run-schism.mjs
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:59:13)
    at Loader.resolve (internal/modules/esm/loader.js:73:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:149:40)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:43:40)
    at link (internal/modules/esm/module_job.js:42:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

```

**Comment by eholk** [comment]
Oh, thanks for trying this out. `schism.sh` is the right way to do this, but it looks like we broke it somewhere along the way.

Until that's fixed, you can get some of what you want with `run-tests.sh`. If you do `run-tests.sh test/lambda-1.ss` then it will run that one test case, but it also leaves behind a `test.wasm` file which will have the Wasm bytes for the compiled test case.
